/**
 * Names of the adapter's objects (common.name) in all languages of the ioBroker admin.
 * "{0}" is a placeholder that objectName() replaces, e.g. with a zone or datapoint number.
 */

/** Languages of the ioBroker admin */
export const LANGUAGES = ["en", "de", "ru", "pt", "nl", "fr", "it", "es", "pl", "uk", "zh-cn"] as const;
export type Language = (typeof LANGUAGES)[number];

/** A text in every admin language */
export type Translations = Record<Language, string>;

export const OBJECT_NAMES = {
    on: {
        en: "On / off",
        de: "Ein / Aus",
        ru: "Вкл. / выкл.",
        pt: "Ligar / desligar",
        nl: "Aan / uit",
        fr: "Marche / arrêt",
        it: "Acceso / spento",
        es: "Encendido / apagado",
        pl: "Wł. / wył.",
        uk: "Увімк. / вимк.",
        "zh-cn": "开 / 关",
    },
    mode: {
        en: "Mode",
        de: "Modus",
        ru: "Режим",
        pt: "Modo",
        nl: "Modus",
        fr: "Mode",
        it: "Modalità",
        es: "Modo",
        pl: "Tryb",
        uk: "Режим",
        "zh-cn": "模式",
    },
    scene: {
        en: "Scene M1–M9 (0 = no scene)",
        de: "Szene M1–M9 (0 = keine Szene)",
        ru: "Сцена M1–M9 (0 = без сцены)",
        pt: "Cena M1–M9 (0 = sem cena)",
        nl: "Scène M1–M9 (0 = geen scène)",
        fr: "Scène M1–M9 (0 = aucune scène)",
        it: "Scena M1–M9 (0 = nessuna scena)",
        es: "Escena M1–M9 (0 = sin escena)",
        pl: "Scena M1–M9 (0 = brak sceny)",
        uk: "Сцена M1–M9 (0 = без сцени)",
        "zh-cn": "场景 M1–M9（0 = 无场景）",
    },
    brightness: {
        en: "Brightness",
        de: "Helligkeit",
        ru: "Яркость",
        pt: "Brilho",
        nl: "Helderheid",
        fr: "Luminosité",
        it: "Luminosità",
        es: "Brillo",
        pl: "Jasność",
        uk: "Яскравість",
        "zh-cn": "亮度",
    },
    colorTemperature: {
        en: "Colour temperature (white mode)",
        de: "Farbtemperatur (Weißmodus)",
        ru: "Цветовая температура (белый режим)",
        pt: "Temperatura de cor (modo branco)",
        nl: "Kleurtemperatuur (witmodus)",
        fr: "Température de couleur (mode blanc)",
        it: "Temperatura di colore (modalità bianco)",
        es: "Temperatura de color (modo blanco)",
        pl: "Temperatura barwowa (tryb białego)",
        uk: "Колірна температура (білий режим)",
        "zh-cn": "色温（白光模式）",
    },
    color: {
        en: "Colour #rrggbb (colour mode)",
        de: "Farbe #rrggbb (Farbmodus)",
        ru: "Цвет #rrggbb (цветной режим)",
        pt: "Cor #rrggbb (modo de cor)",
        nl: "Kleur #rrggbb (kleurmodus)",
        fr: "Couleur #rrggbb (mode couleur)",
        it: "Colore #rrggbb (modalità colore)",
        es: "Color #rrggbb (modo color)",
        pl: "Kolor #rrggbb (tryb koloru)",
        uk: "Колір #rrggbb (кольоровий режим)",
        "zh-cn": "颜色 #rrggbb（彩色模式）",
    },
    hue: {
        en: "Hue (colour mode)",
        de: "Farbton (Farbmodus)",
        ru: "Оттенок (цветной режим)",
        pt: "Matiz (modo de cor)",
        nl: "Tint (kleurmodus)",
        fr: "Teinte (mode couleur)",
        it: "Tonalità (modalità colore)",
        es: "Tono (modo color)",
        pl: "Odcień (tryb koloru)",
        uk: "Відтінок (кольоровий режим)",
        "zh-cn": "色调（彩色模式）",
    },
    saturation: {
        en: "Saturation (colour mode)",
        de: "Sättigung (Farbmodus)",
        ru: "Насыщенность (цветной режим)",
        pt: "Saturação (modo de cor)",
        nl: "Verzadiging (kleurmodus)",
        fr: "Saturation (mode couleur)",
        it: "Saturazione (modalità colore)",
        es: "Saturación (modo color)",
        pl: "Nasycenie (tryb koloru)",
        uk: "Насиченість (кольоровий режим)",
        "zh-cn": "饱和度（彩色模式）",
    },
    speedUp: {
        en: "Scene faster (S+)",
        de: "Szene schneller (S+)",
        ru: "Сцена быстрее (S+)",
        pt: "Cena mais rápida (S+)",
        nl: "Scène sneller (S+)",
        fr: "Scène plus rapide (S+)",
        it: "Scena più veloce (S+)",
        es: "Escena más rápida (S+)",
        pl: "Scena szybciej (S+)",
        uk: "Сцена швидше (S+)",
        "zh-cn": "场景加速（S+）",
    },
    speedDown: {
        en: "Scene slower (S-)",
        de: "Szene langsamer (S-)",
        ru: "Сцена медленнее (S-)",
        pt: "Cena mais lenta (S-)",
        nl: "Scène langzamer (S-)",
        fr: "Scène plus lente (S-)",
        it: "Scena più lenta (S-)",
        es: "Escena más lenta (S-)",
        pl: "Scena wolniej (S-)",
        uk: "Сцена повільніше (S-)",
        "zh-cn": "场景减速（S-）",
    },
    ip: {
        en: "IP address of the gateway",
        de: "IP-Adresse des Gateways",
        ru: "IP-адрес шлюза",
        pt: "Endereço IP do gateway",
        nl: "IP-adres van de gateway",
        fr: "Adresse IP de la passerelle",
        it: "Indirizzo IP del gateway",
        es: "Dirección IP de la pasarela",
        pl: "Adres IP bramki",
        uk: "IP-адреса шлюзу",
        "zh-cn": "网关的 IP 地址",
    },
    countdown: {
        en: "Countdown until toggle (DP 26)",
        de: "Countdown bis zum Umschalten (DP 26)",
        ru: "Обратный отсчёт до переключения (DP 26)",
        pt: "Contagem decrescente até alternar (DP 26)",
        nl: "Aftellen tot omschakelen (DP 26)",
        fr: "Compte à rebours avant basculement (DP 26)",
        it: "Conto alla rovescia fino alla commutazione (DP 26)",
        es: "Cuenta atrás hasta conmutar (DP 26)",
        pl: "Odliczanie do przełączenia (DP 26)",
        uk: "Зворотний відлік до перемикання (DP 26)",
        "zh-cn": "切换倒计时（DP 26）",
    },
    dp101: {
        en: "Datapoint 101 (raw frames of zones, scenes and status)",
        de: "Datenpunkt 101 (Roh-Frames für Zonen, Szenen und Status)",
        ru: "Точка данных 101 (сырые кадры зон, сцен и состояния)",
        pt: "Ponto de dados 101 (frames brutos de zonas, cenas e estado)",
        nl: "Datapunt 101 (ruwe frames van zones, scènes en status)",
        fr: "Point de données 101 (trames brutes des zones, scènes et état)",
        it: "Punto dati 101 (frame grezzi di zone, scene e stato)",
        es: "Punto de datos 101 (tramas sin procesar de zonas, escenas y estado)",
        pl: "Punkt danych 101 (surowe ramki stref, scen i stanu)",
        uk: "Точка даних 101 (сирі кадри зон, сцен і стану)",
        "zh-cn": "数据点 101（区域、场景和状态的原始帧）",
    },
    dp101Raw: {
        en: "Last frame as Base64 (writable)",
        de: "Letzter Frame als Base64 (schreibbar)",
        ru: "Последний кадр в Base64 (доступен для записи)",
        pt: "Último frame em Base64 (gravável)",
        nl: "Laatste frame als Base64 (schrijfbaar)",
        fr: "Dernière trame en Base64 (modifiable)",
        it: "Ultimo frame in Base64 (scrivibile)",
        es: "Última trama en Base64 (escribible)",
        pl: "Ostatnia ramka jako Base64 (zapisywalna)",
        uk: "Останній кадр у Base64 (доступний для запису)",
        "zh-cn": "最后一帧，Base64（可写）",
    },
    dp101Hex: {
        en: "Last frame as hex (writable, checksum is added automatically)",
        de: "Letzter Frame als Hex (schreibbar, Prüfsumme wird automatisch ergänzt)",
        ru: "Последний кадр в hex (доступен для записи, контрольная сумма добавляется автоматически)",
        pt: "Último frame em hex (gravável, a soma de verificação é adicionada automaticamente)",
        nl: "Laatste frame als hex (schrijfbaar, controlesom wordt automatisch toegevoegd)",
        fr: "Dernière trame en hexadécimal (modifiable, la somme de contrôle est ajoutée automatiquement)",
        it: "Ultimo frame in esadecimale (scrivibile, il checksum viene aggiunto automaticamente)",
        es: "Última trama en hexadecimal (escribible, la suma de comprobación se añade automáticamente)",
        pl: "Ostatnia ramka jako hex (zapisywalna, suma kontrolna jest dodawana automatycznie)",
        uk: "Останній кадр у hex (доступний для запису, контрольна сума додається автоматично)",
        "zh-cn": "最后一帧，十六进制（可写，自动添加校验和）",
    },
    dp101ChecksumValid: {
        en: "Checksum of the last frame is valid",
        de: "Prüfsumme des letzten Frames ist gültig",
        ru: "Контрольная сумма последнего кадра верна",
        pt: "A soma de verificação do último frame é válida",
        nl: "Controlesom van het laatste frame is geldig",
        fr: "La somme de contrôle de la dernière trame est valide",
        it: "Il checksum dell'ultimo frame è valido",
        es: "La suma de comprobación de la última trama es válida",
        pl: "Suma kontrolna ostatniej ramki jest poprawna",
        uk: "Контрольна сума останнього кадру правильна",
        "zh-cn": "最后一帧的校验和有效",
    },
    dp101History: {
        en: "Last {0} frames (received and sent)",
        de: "Letzte {0} Frames (empfangen und gesendet)",
        ru: "Последние {0} кадров (полученные и отправленные)",
        pt: "Últimos {0} frames (recebidos e enviados)",
        nl: "Laatste {0} frames (ontvangen en verzonden)",
        fr: "{0} dernières trames (reçues et envoyées)",
        it: "Ultimi {0} frame (ricevuti e inviati)",
        es: "Últimas {0} tramas (recibidas y enviadas)",
        pl: "Ostatnie {0} ramek (odebrane i wysłane)",
        uk: "Останні {0} кадрів (отримані та надіслані)",
        "zh-cn": "最近 {0} 帧（接收和发送）",
    },
    raw: {
        en: "Other datapoints",
        de: "Weitere Datenpunkte",
        ru: "Другие точки данных",
        pt: "Outros pontos de dados",
        nl: "Overige datapunten",
        fr: "Autres points de données",
        it: "Altri punti dati",
        es: "Otros puntos de datos",
        pl: "Inne punkty danych",
        uk: "Інші точки даних",
        "zh-cn": "其他数据点",
    },
    rawDatapoint: {
        en: "Datapoint {0}",
        de: "Datenpunkt {0}",
        ru: "Точка данных {0}",
        pt: "Ponto de dados {0}",
        nl: "Datapunt {0}",
        fr: "Point de données {0}",
        it: "Punto dati {0}",
        es: "Punto de datos {0}",
        pl: "Punkt danych {0}",
        uk: "Точка даних {0}",
        "zh-cn": "数据点 {0}",
    },
    settings: {
        en: "Gateway settings",
        de: "Gateway-Einstellungen",
        ru: "Настройки шлюза",
        pt: "Definições do gateway",
        nl: "Gateway-instellingen",
        fr: "Paramètres de la passerelle",
        it: "Impostazioni del gateway",
        es: "Ajustes de la pasarela",
        pl: "Ustawienia bramki",
        uk: "Налаштування шлюзу",
        "zh-cn": "网关设置",
    },
    dmxAddress: {
        en: "DMX start address (5 channels: R, G, B, cold white, warm white)",
        de: "DMX-Startadresse (5 Kanäle: R, G, B, Kaltweiß, Warmweiß)",
        ru: "Начальный адрес DMX (5 каналов: R, G, B, холодный белый, тёплый белый)",
        pt: "Endereço inicial DMX (5 canais: R, G, B, branco frio, branco quente)",
        nl: "DMX-startadres (5 kanalen: R, G, B, koud wit, warm wit)",
        fr: "Adresse de départ DMX (5 canaux : R, G, B, blanc froid, blanc chaud)",
        it: "Indirizzo iniziale DMX (5 canali: R, G, B, bianco freddo, bianco caldo)",
        es: "Dirección de inicio DMX (5 canales: R, G, B, blanco frío, blanco cálido)",
        pl: "Adres startowy DMX (5 kanałów: R, G, B, zimna biel, ciepła biel)",
        uk: "Початкова адреса DMX (5 каналів: R, G, B, холодний білий, теплий білий)",
        "zh-cn": "DMX 起始地址（5 个通道：R、G、B、冷白、暖白）",
    },
    timers: {
        en: "Timers (tab Timers in the instance settings)",
        de: "Timer (Reiter Timer in den Instanzeinstellungen)",
        ru: "Таймеры (вкладка «Таймеры» в настройках экземпляра)",
        pt: "Temporizadores (separador Temporizadores nas definições da instância)",
        nl: "Timers (tabblad Timers in de instantie-instellingen)",
        fr: "Minuteries (onglet Minuteries des paramètres de l'instance)",
        it: "Timer (scheda Timer nelle impostazioni dell'istanza)",
        es: "Temporizadores (pestaña Temporizadores en los ajustes de la instancia)",
        pl: "Timery (karta Timery w ustawieniach instancji)",
        uk: "Таймери (вкладка «Таймери» в налаштуваннях екземпляра)",
        "zh-cn": "定时器（实例设置中的“定时器”选项卡）",
    },
    timersActive: {
        en: "Timers active (false = all timers paused)",
        de: "Timer aktiv (false = alle Timer pausiert)",
        ru: "Таймеры активны (false = все таймеры приостановлены)",
        pt: "Temporizadores ativos (false = todos os temporizadores em pausa)",
        nl: "Timers actief (false = alle timers gepauzeerd)",
        fr: "Minuteries actives (false = toutes les minuteries en pause)",
        it: "Timer attivi (false = tutti i timer in pausa)",
        es: "Temporizadores activos (false = todos los temporizadores en pausa)",
        pl: "Timery aktywne (false = wszystkie timery wstrzymane)",
        uk: "Таймери активні (false = усі таймери призупинено)",
        "zh-cn": "定时器已启用（false = 暂停所有定时器）",
    },
    timersNextRun: {
        en: "Next timer run",
        de: "Nächste Timer-Ausführung",
        ru: "Следующее срабатывание таймера",
        pt: "Próxima execução do temporizador",
        nl: "Volgende uitvoering van een timer",
        fr: "Prochaine exécution d'une minuterie",
        it: "Prossima esecuzione del timer",
        es: "Próxima ejecución del temporizador",
        pl: "Następne uruchomienie timera",
        uk: "Наступне спрацювання таймера",
        "zh-cn": "下次定时器运行",
    },
    timersLastRun: {
        en: "Last timer run",
        de: "Letzte Timer-Ausführung",
        ru: "Последнее срабатывание таймера",
        pt: "Última execução do temporizador",
        nl: "Laatste uitvoering van een timer",
        fr: "Dernière exécution d'une minuterie",
        it: "Ultima esecuzione del timer",
        es: "Última ejecución del temporizador",
        pl: "Ostatnie uruchomienie timera",
        uk: "Останнє спрацювання таймера",
        "zh-cn": "上次定时器运行",
    },
    timersOverview: {
        en: "All timers (max. {0}) with their next run",
        de: "Alle Timer (max. {0}) mit nächster Ausführung",
        ru: "Все таймеры (макс. {0}) со следующим срабатыванием",
        pt: "Todos os temporizadores (máx. {0}) com a próxima execução",
        nl: "Alle timers (max. {0}) met hun volgende uitvoering",
        fr: "Toutes les minuteries (max. {0}) avec leur prochaine exécution",
        it: "Tutti i timer (max. {0}) con la prossima esecuzione",
        es: "Todos los temporizadores (máx. {0}) con su próxima ejecución",
        pl: "Wszystkie timery (maks. {0}) z następnym uruchomieniem",
        uk: "Усі таймери (макс. {0}) з наступним спрацюванням",
        "zh-cn": "所有定时器（最多 {0} 个）及其下次运行",
    },
    lightSelector: {
        en: "Pool lights (status of the gateway, commands to the zone in light.zone)",
        de: "Poolleuchten (Status des Gateways, Befehle an die Zone in light.zone)",
        ru: "Освещение бассейна (состояние шлюза, команды в зону из light.zone)",
        pt: "Luzes da piscina (estado do gateway, comandos para a zona em light.zone)",
        nl: "Zwembadverlichting (status van de gateway, opdrachten naar de zone in light.zone)",
        fr: "Éclairage de piscine (état de la passerelle, commandes vers la zone de light.zone)",
        it: "Luci della piscina (stato del gateway, comandi alla zona in light.zone)",
        es: "Luces de la piscina (estado de la pasarela, órdenes a la zona de light.zone)",
        pl: "Oświetlenie basenu (stan bramki, polecenia do strefy z light.zone)",
        uk: "Освітлення басейну (стан шлюзу, команди до зони з light.zone)",
        "zh-cn": "泳池灯（网关状态，命令发送到 light.zone 中的区域）",
    },
    lightAllZones: {
        en: "Pool lights (status of the gateway, commands to all zones)",
        de: "Poolleuchten (Status des Gateways, Befehle an alle Zonen)",
        ru: "Освещение бассейна (состояние шлюза, команды во все зоны)",
        pt: "Luzes da piscina (estado do gateway, comandos para todas as zonas)",
        nl: "Zwembadverlichting (status van de gateway, opdrachten naar alle zones)",
        fr: "Éclairage de piscine (état de la passerelle, commandes vers toutes les zones)",
        it: "Luci della piscina (stato del gateway, comandi a tutte le zone)",
        es: "Luces de la piscina (estado de la pasarela, órdenes a todas las zonas)",
        pl: "Oświetlenie basenu (stan bramki, polecenia do wszystkich stref)",
        uk: "Освітлення басейну (стан шлюзу, команди до всіх зон)",
        "zh-cn": "泳池灯（网关状态，命令发送到所有区域）",
    },
    zoneSelector: {
        en: "Zone for the commands of light.* (0 = all zones)",
        de: "Zone für die Befehle von light.* (0 = alle Zonen)",
        ru: "Зона для команд light.* (0 = все зоны)",
        pt: "Zona para os comandos de light.* (0 = todas as zonas)",
        nl: "Zone voor de opdrachten van light.* (0 = alle zones)",
        fr: "Zone des commandes de light.* (0 = toutes les zones)",
        it: "Zona per i comandi di light.* (0 = tutte le zone)",
        es: "Zona para las órdenes de light.* (0 = todas las zonas)",
        pl: "Strefa dla poleceń light.* (0 = wszystkie strefy)",
        uk: "Зона для команд light.* (0 = усі зони)",
        "zh-cn": "light.* 命令的区域（0 = 所有区域）",
    },
    zones: {
        en: "Zones (last values sent)",
        de: "Zonen (zuletzt gesendete Werte)",
        ru: "Зоны (последние отправленные значения)",
        pt: "Zonas (últimos valores enviados)",
        nl: "Zones (laatst verzonden waarden)",
        fr: "Zones (dernières valeurs envoyées)",
        it: "Zone (ultimi valori inviati)",
        es: "Zonas (últimos valores enviados)",
        pl: "Strefy (ostatnio wysłane wartości)",
        uk: "Зони (останні надіслані значення)",
        "zh-cn": "区域（最后发送的值）",
    },
    zone: {
        en: "Zone {0}",
        de: "Zone {0}",
        ru: "Зона {0}",
        pt: "Zona {0}",
        nl: "Zone {0}",
        fr: "Zone {0}",
        it: "Zona {0}",
        es: "Zona {0}",
        pl: "Strefa {0}",
        uk: "Зона {0}",
        "zh-cn": "区域 {0}",
    },
} satisfies Record<string, Translations>;

export type ObjectNameKey = keyof typeof OBJECT_NAMES;

/**
 * Name of an object in all admin languages.
 *
 * @param key - entry of OBJECT_NAMES
 * @param value - replaces "{0}", e.g. a zone or datapoint number
 */
export function objectName(key: ObjectNameKey, value?: string | number): Translations {
    const names: Translations = OBJECT_NAMES[key];
    const result = {} as Translations;
    for (const language of LANGUAGES) {
        result[language] = value === undefined ? names[language] : names[language].replace("{0}", String(value));
    }
    return result;
}
